name: zak-visuals-multiprocess

channels:
- conda-forge
- defaults

dependencies:
- python=3.7
- tensorflow-gpu=1.15
- cudatoolkit=10.0
- pip
- requests
- librosa
- pip:
  - git+https://github.com/jackersson/gstreamer-python.git#egg=gstreamer-python
  - python-osc
